[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8", features = ["macros"]}
tokio = {version = "1.43.0", features = ["full"]}
sqlx = {version = "0.8.6", features = ["sqlite", "runtime-tokio-rustls", "macros"]}
chrono = "0.4.41"
serde = "1.0.219"
