[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = {version = "1.43.0", features = ["full"]}
sqlx = {version = "0.8.6", features = ["sqlite", "runtime-tokio-rustls"]}